project_id = "upgonsupucpgonhhanjd"

[functions.analyze-image]
verify_jwt = false

[functions.get-recommendations]
verify_jwt = false

[functions.spotify-auth]
verify_jwt = false

[functions.analyze-music]
verify_jwt = false
